easy_admin:
  design:
    brand_color: '#1ABC9C'

    menu:
      - label: 'blogSymfony'
        icon: 'newspaper-o'
        children:
          - {entity: 'Article', icon: 'folder-open', label: 'Articles'}
          - {entity: 'Category', icon: 'folder-open', label: 'Catégories'}

      - label: 'Accès'
        icon: 'user'
        children:
          - {entity: 'User', icon: 'folder-open', label: 'Utilisateurs'}